version: '3'

services:
  db:
    image: postgres:latest
    container_name: feedget_db
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedget
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgres
    restart: unless-stopped

volumes:
  db:
    driver: local
